preload = /home/iader/Downloads/noche-colorida-en-las-montanas-arte-digital_1920x1080_xtrafondos.com.jpg
wallpaper = eDP-1,/home/iader/Downloads/noche-colorida-en-las-montanas-arte-digital_1920x1080_xtrafondos.com.jpg
