# Forzar aceleración por hardware para gráficas AMD
hwdec=vaapi
vo=gpu

# Estética minimalista (sin barras de título de ventana clásica)
border=no

# Guardar la posición del video si lo cierras (para seguir viéndolo después)
save-position-on-quit=yes

# Idioma predeterminado para audio y subtítulos
alang=es,en
slang=es,en
